require("DreamLineLove.plugins-setup")
require("DreamLineLove.core.options")
require("DreamLineLove.core.keymaps")
require("DreamLineLove.core.colorscheme")

require("DreamLineLove.plugins.comment")
require("DreamLineLove.plugins.nvim-tree")
require("DreamLineLove.plugins.lualine")
require("DreamLineLove.plugins.telescope")
require("DreamLineLove.plugins.nvim-cmp")

require("DreamLineLove.plugins.lsp.mason")
require("DreamLineLove.plugins.lsp.lspsaga")
require("DreamLineLove.plugins.lsp.lspconfig")
require("DreamLineLove.plugins.lsp.null-ls")

require("DreamLineLove.plugins.autopairs")
require("DreamLineLove.plugins.treesitter")
require("DreamLineLove.plugins.gitsigns")
require("DreamLineLove.plugins.undotree")
